[tool.poetry]
name = "codefreaker"
version = "0.1.0"
description = ""
authors = ["Roberto Sales <rsalescaldeira@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
typer = {extras = ["all"], version = "^0.12.3"}
fastapi = "^0.111.0"
filelock = "^3.14.0"
gevent = "^24.2.1"
mechanize = "^0.4.10"
jinja2 = "^3.1.4"

[tool.poetry.scripts]
cfk = "codefreaker.main:app"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
